import { FunctionComponent } from "react";
import Dots from "./Dots";
import Footer from "./Footer";
import H1 from "./H1";
import Block from "./Block";
import Fact from "./Fact";
import Header from "./Header";
import Media from "./Media";
import styles from "./About.module.css";

export type AboutType = {
  className?: string;
};

const About: FunctionComponent<AboutType> = ({ className = "" }) => {
  return (
    <div className={[styles.about, className].join(" ")}>
      <div className={styles.background}>
        <Dots
          showEllipseDiv
          ellipseDivVisible
          ellipseDivVisible1
          showFrameDiv
          ellipseDivVisible2
          frameDivVisible
          dotsWidth="103px"
          dotsHeight="103px"
          dotsPosition="absolute"
          dotsTop="1134px"
          dotsLeft="1363px"
          ellipseDivWidth="4px"
          ellipseDivHeight="4px"
          ellipseDivWidth1="4px"
          ellipseDivHeight1="4px"
          ellipseDivWidth2="4px"
          ellipseDivHeight2="4px"
          ellipseDivWidth3="4px"
          ellipseDivHeight3="4px"
          ellipseDivWidth4="4px"
          ellipseDivHeight4="4px"
          ellipseDivWidth5="4px"
          ellipseDivHeight5="4px"
          ellipseDivWidth6="4px"
          ellipseDivHeight6="4px"
          ellipseDivWidth7="4px"
          ellipseDivHeight7="4px"
          ellipseDivWidth8="4px"
          ellipseDivHeight8="4px"
          ellipseDivWidth9="4px"
          ellipseDivHeight9="4px"
          ellipseDivWidth10="4px"
          ellipseDivHeight10="4px"
          ellipseDivWidth11="4px"
          ellipseDivHeight11="4px"
          ellipseDivWidth12="4px"
          ellipseDivHeight12="4px"
          ellipseDivWidth13="4px"
          ellipseDivHeight13="4px"
          ellipseDivWidth14="4px"
          ellipseDivHeight14="4px"
          frameDivAlignSelf="stretch"
          frameDivWidth="unset"
          ellipseDivWidth15="4px"
          ellipseDivHeight15="4px"
          ellipseDivWidth16="4px"
          ellipseDivHeight16="4px"
          ellipseDivWidth17="4px"
          ellipseDivHeight17="4px"
          ellipseDivWidth18="4px"
          ellipseDivHeight18="4px"
          ellipseDivWidth19="4px"
          ellipseDivHeight19="4px"
          frameDivAlignSelf1="stretch"
          frameDivWidth1="unset"
          ellipseDivWidth20="4px"
          ellipseDivHeight20="4px"
          ellipseDivWidth21="4px"
          ellipseDivHeight21="4px"
          ellipseDivWidth22="4px"
          ellipseDivHeight22="4px"
          ellipseDivWidth23="4px"
          ellipseDivHeight23="4px"
          ellipseDivWidth24="4px"
          ellipseDivHeight24="4px"
        />
        <Dots
          showEllipseDiv
          ellipseDivVisible
          ellipseDivVisible1
          showFrameDiv
          ellipseDivVisible2
          frameDivVisible
          dotsWidth="103px"
          dotsHeight="103px"
          dotsPosition="absolute"
          dotsTop="511px"
          dotsLeft="1390px"
          ellipseDivWidth="4px"
          ellipseDivHeight="4px"
          ellipseDivWidth1="4px"
          ellipseDivHeight1="4px"
          ellipseDivWidth2="4px"
          ellipseDivHeight2="4px"
          ellipseDivWidth3="4px"
          ellipseDivHeight3="4px"
          ellipseDivWidth4="4px"
          ellipseDivHeight4="4px"
          ellipseDivWidth5="4px"
          ellipseDivHeight5="4px"
          ellipseDivWidth6="4px"
          ellipseDivHeight6="4px"
          ellipseDivWidth7="4px"
          ellipseDivHeight7="4px"
          ellipseDivWidth8="4px"
          ellipseDivHeight8="4px"
          ellipseDivWidth9="4px"
          ellipseDivHeight9="4px"
          ellipseDivWidth10="4px"
          ellipseDivHeight10="4px"
          ellipseDivWidth11="4px"
          ellipseDivHeight11="4px"
          ellipseDivWidth12="4px"
          ellipseDivHeight12="4px"
          ellipseDivWidth13="4px"
          ellipseDivHeight13="4px"
          ellipseDivWidth14="4px"
          ellipseDivHeight14="4px"
          frameDivAlignSelf="stretch"
          frameDivWidth="unset"
          ellipseDivWidth15="4px"
          ellipseDivHeight15="4px"
          ellipseDivWidth16="4px"
          ellipseDivHeight16="4px"
          ellipseDivWidth17="4px"
          ellipseDivHeight17="4px"
          ellipseDivWidth18="4px"
          ellipseDivHeight18="4px"
          ellipseDivWidth19="4px"
          ellipseDivHeight19="4px"
          frameDivAlignSelf1="stretch"
          frameDivWidth1="unset"
          ellipseDivWidth20="4px"
          ellipseDivHeight20="4px"
          ellipseDivWidth21="4px"
          ellipseDivHeight21="4px"
          ellipseDivWidth22="4px"
          ellipseDivHeight22="4px"
          ellipseDivWidth23="4px"
          ellipseDivHeight23="4px"
          ellipseDivWidth24="4px"
          ellipseDivHeight24="4px"
        />
        <Dots
          showEllipseDiv
          ellipseDivVisible
          ellipseDivVisible1
          showFrameDiv={false}
          ellipseDivVisible2
          frameDivVisible
          dotsWidth="109px"
          dotsHeight="49px"
          dotsPosition="absolute"
          dotsTop="145px"
          dotsLeft="46px"
          ellipseDivWidth="4px"
          ellipseDivHeight="4px"
          ellipseDivWidth1="4px"
          ellipseDivHeight1="4px"
          ellipseDivWidth2="4px"
          ellipseDivHeight2="4px"
          ellipseDivWidth3="4px"
          ellipseDivHeight3="4px"
          ellipseDivWidth4="4px"
          ellipseDivHeight4="4px"
          ellipseDivWidth5="4px"
          ellipseDivHeight5="4px"
          ellipseDivWidth6="4px"
          ellipseDivHeight6="4px"
          ellipseDivWidth7="4px"
          ellipseDivHeight7="4px"
          ellipseDivWidth8="4px"
          ellipseDivHeight8="4px"
          ellipseDivWidth9="4px"
          ellipseDivHeight9="4px"
          ellipseDivWidth10="4px"
          ellipseDivHeight10="4px"
          ellipseDivWidth11="4px"
          ellipseDivHeight11="4px"
          ellipseDivWidth12="4px"
          ellipseDivHeight12="4px"
          ellipseDivWidth13="4px"
          ellipseDivHeight13="4px"
          ellipseDivWidth14="4px"
          ellipseDivHeight14="4px"
          frameDivAlignSelf="unset"
          frameDivWidth="84px"
          ellipseDivWidth15="4px"
          ellipseDivHeight15="4px"
          ellipseDivWidth16="4px"
          ellipseDivHeight16="4px"
          ellipseDivWidth17="4px"
          ellipseDivHeight17="4px"
          ellipseDivWidth18="4px"
          ellipseDivHeight18="4px"
          ellipseDivWidth19="4px"
          ellipseDivHeight19="4px"
          frameDivAlignSelf1="stretch"
          frameDivWidth1="unset"
          ellipseDivWidth20="4px"
          ellipseDivHeight20="4px"
          ellipseDivWidth21="4px"
          ellipseDivHeight21="4px"
          ellipseDivWidth22="4px"
          ellipseDivHeight22="4px"
          ellipseDivWidth23="4px"
          ellipseDivHeight23="4px"
          ellipseDivWidth24="4px"
          ellipseDivHeight24="4px"
        />
        <div className={styles.backgroundChild} />
        <div className={styles.backgroundItem} />
      </div>
      <Footer logo="/logo@2x.png" propLeft="calc(50% - 683px)" />
      <div className={styles.title}>
        <div className={styles.parent}>
          <div className={styles.div}>/</div>
          <div className={styles.aboutMe}>about-me</div>
        </div>
        <div className={styles.whoAmI}>Who am i?</div>
      </div>
      <div className={styles.about1}>
        <div className={styles.jcGellidonE3numcscugoUnsplaParent}>
          <img
            className={styles.jcGellidonE3numcscugoUnsplaIcon}
            alt=""
            src="/image@2x.png"
          />
          <Dots
            showEllipseDiv
            ellipseDivVisible
            ellipseDivVisible1
            showFrameDiv
            ellipseDivVisible2
            frameDivVisible
            dotsWidth="84px"
            dotsHeight="84px"
            dotsPosition="absolute"
            dotsTop="59px"
            dotsLeft="0px"
            ellipseDivWidth="4px"
            ellipseDivHeight="4px"
            ellipseDivWidth1="4px"
            ellipseDivHeight1="4px"
            ellipseDivWidth2="4px"
            ellipseDivHeight2="4px"
            ellipseDivWidth3="4px"
            ellipseDivHeight3="4px"
            ellipseDivWidth4="4px"
            ellipseDivHeight4="4px"
            ellipseDivWidth5="4px"
            ellipseDivHeight5="4px"
            ellipseDivWidth6="4px"
            ellipseDivHeight6="4px"
            ellipseDivWidth7="4px"
            ellipseDivHeight7="4px"
            ellipseDivWidth8="4px"
            ellipseDivHeight8="4px"
            ellipseDivWidth9="4px"
            ellipseDivHeight9="4px"
            ellipseDivWidth10="4px"
            ellipseDivHeight10="4px"
            ellipseDivWidth11="4px"
            ellipseDivHeight11="4px"
            ellipseDivWidth12="4px"
            ellipseDivHeight12="4px"
            ellipseDivWidth13="4px"
            ellipseDivHeight13="4px"
            ellipseDivWidth14="4px"
            ellipseDivHeight14="4px"
            frameDivAlignSelf="stretch"
            frameDivWidth="unset"
            ellipseDivWidth15="4px"
            ellipseDivHeight15="4px"
            ellipseDivWidth16="4px"
            ellipseDivHeight16="4px"
            ellipseDivWidth17="4px"
            ellipseDivHeight17="4px"
            ellipseDivWidth18="4px"
            ellipseDivHeight18="4px"
            ellipseDivWidth19="4px"
            ellipseDivHeight19="4px"
            frameDivAlignSelf1="stretch"
            frameDivWidth1="unset"
            ellipseDivWidth20="4px"
            ellipseDivHeight20="4px"
            ellipseDivWidth21="4px"
            ellipseDivHeight21="4px"
            ellipseDivWidth22="4px"
            ellipseDivHeight22="4px"
            ellipseDivWidth23="4px"
            ellipseDivHeight23="4px"
            ellipseDivWidth24="4px"
            ellipseDivHeight24="4px"
          />
          <Dots
            showEllipseDiv
            ellipseDivVisible
            ellipseDivVisible1
            showFrameDiv={false}
            ellipseDivVisible2
            frameDivVisible
            dotsWidth="104px"
            dotsHeight="56px"
            dotsPosition="absolute"
            dotsTop="279px"
            dotsLeft="223px"
            ellipseDivWidth="4px"
            ellipseDivHeight="4px"
            ellipseDivWidth1="4px"
            ellipseDivHeight1="4px"
            ellipseDivWidth2="4px"
            ellipseDivHeight2="4px"
            ellipseDivWidth3="4px"
            ellipseDivHeight3="4px"
            ellipseDivWidth4="4px"
            ellipseDivHeight4="4px"
            ellipseDivWidth5="4px"
            ellipseDivHeight5="4px"
            ellipseDivWidth6="4px"
            ellipseDivHeight6="4px"
            ellipseDivWidth7="4px"
            ellipseDivHeight7="4px"
            ellipseDivWidth8="4px"
            ellipseDivHeight8="4px"
            ellipseDivWidth9="4px"
            ellipseDivHeight9="4px"
            ellipseDivWidth10="4px"
            ellipseDivHeight10="4px"
            ellipseDivWidth11="4px"
            ellipseDivHeight11="4px"
            ellipseDivWidth12="4px"
            ellipseDivHeight12="4px"
            ellipseDivWidth13="4px"
            ellipseDivHeight13="4px"
            ellipseDivWidth14="4px"
            ellipseDivHeight14="4px"
            frameDivAlignSelf="unset"
            frameDivWidth="84px"
            ellipseDivWidth15="4px"
            ellipseDivHeight15="4px"
            ellipseDivWidth16="4px"
            ellipseDivHeight16="4px"
            ellipseDivWidth17="4px"
            ellipseDivHeight17="4px"
            ellipseDivWidth18="4px"
            ellipseDivHeight18="4px"
            ellipseDivWidth19="4px"
            ellipseDivHeight19="4px"
            frameDivAlignSelf1="stretch"
            frameDivWidth1="unset"
            ellipseDivWidth20="4px"
            ellipseDivHeight20="4px"
            ellipseDivWidth21="4px"
            ellipseDivHeight21="4px"
            ellipseDivWidth22="4px"
            ellipseDivHeight22="4px"
            ellipseDivWidth23="4px"
            ellipseDivHeight23="4px"
            ellipseDivWidth24="4px"
            ellipseDivHeight24="4px"
          />
          <img
            className={styles.line7Stroke}
            alt=""
            src="/line-7-stroke2.svg"
          />
        </div>
        <div className={styles.helloImEliasContainer}>
          <p className={styles.helloImElias}>Hello, i’m Elias!</p>
          <p className={styles.helloImElias}>&nbsp;</p>
          <p
            className={styles.helloImElias}
          >{`I’m a self-taught front-end developer based in Kyiv, Ukraine. I can develop responsive websites from scratch and raise them into modern user-friendly web experiences. `}</p>
          <p className={styles.helloImElias}>&nbsp;</p>
          <p className={styles.helloImElias}>
            Transforming my creativity and knowledge into a websites has been my
            passion for over a year. I have been helping various clients to
            establish their presence online. I always strive to learn about the
            newest technologies and frameworks.
          </p>
        </div>
      </div>
      <div className={styles.skills}>
        <H1
          categoryLabel="skills"
          propTop="0px"
          propLeft="0px"
          propHeight="unset"
          propWidth="unset"
          propRight="unset"
          propBottom="unset"
          propFontSize="32px"
          propFontSize1="32px"
        />
        <div className={styles.blockParent}>
          <Block
            languages="Languages"
            typeScript="TypeScript"
            lua="Lua"
            lua1="Lua"
            lua3="Lua"
            python="Python"
            javaScript="JavaScript"
            javaScript1="JavaScript"
            python1="Python"
            javaScript3="JavaScript"
            python2="Python"
            javaScript4="JavaScript"
            lua2={false}
            lua4={false}
            showJavaScript
            javaScript2={false}
            frameDiv={false}
            javaScriptVisible
            frameDiv1={false}
            propLeft="unset"
            propTop="unset"
            propWidth="unset"
            propPosition="unset"
            propFlex="1"
            propWidth1="29px"
            propWidth2="29px"
            propWidth3="unset"
            propWidth4="96px"
            propWidth5="unset"
          />
          <Block
            languages="Other"
            typeScript="HTML"
            lua="CSS"
            lua1="EJS"
            lua3="SCSS"
            python="REST"
            javaScript="Jinja"
            javaScript1="JavaScript"
            python1="Jinja"
            javaScript3="Express.js"
            python2="Python"
            javaScript4="JavaScript"
            lua2
            lua4
            showJavaScript
            javaScript2={false}
            frameDiv={false}
            javaScriptVisible={false}
            frameDiv1={false}
            propLeft="unset"
            propTop="unset"
            propWidth="unset"
            propPosition="unset"
            propFlex="1"
            propWidth1="unset"
            propWidth2="unset"
            propWidth3="unset"
            propWidth4="96px"
            propWidth5="96px"
          />
          <Block
            languages="Tools"
            typeScript="VSCode"
            lua="Neovim"
            lua1="Lua"
            lua3="Linux"
            python="Figma"
            javaScript="XFCE"
            javaScript1="Arch"
            python1="Git"
            javaScript3="Font Awesome"
            python2="KDE"
            javaScript4="fish"
            lua2={false}
            lua4
            showJavaScript
            javaScript2
            frameDiv
            javaScriptVisible
            frameDiv1
            propLeft="unset"
            propTop="unset"
            propWidth="unset"
            propPosition="unset"
            propFlex="1"
            propWidth1="29px"
            propWidth2="unset"
            propWidth3="unset"
            propWidth4="unset"
            propWidth5="unset"
          />
          <Block
            languages="Databases"
            typeScript="SQLite"
            lua="PostgreSQL"
            lua1="Lua"
            lua3="Lua"
            python="Mongo"
            javaScript="avaScript"
            javaScript1="JavaScript"
            python1="Python"
            javaScript3="JavaScript"
            python2="Python"
            javaScript4="JavaScript"
            lua2={false}
            lua4={false}
            showJavaScript={false}
            javaScript2={false}
            frameDiv={false}
            javaScriptVisible
            frameDiv1={false}
            propLeft="unset"
            propTop="unset"
            propWidth="unset"
            propPosition="unset"
            propFlex="1"
            propWidth1="29px"
            propWidth2="29px"
            propWidth3="87px"
            propWidth4="96px"
            propWidth5="unset"
          />
          <Block
            languages="Frameworks"
            typeScript="React"
            lua="Vue"
            lua1="Lua"
            lua3="Lua"
            python="Disnake"
            javaScript="Discord.js"
            javaScript1="JavaScript"
            python1="Flask"
            javaScript3="Express.js"
            python2="Python"
            javaScript4="JavaScript"
            lua2={false}
            lua4={false}
            showJavaScript
            javaScript2={false}
            frameDiv
            javaScriptVisible
            frameDiv1={false}
            propLeft="unset"
            propTop="unset"
            propWidth="unset"
            propPosition="unset"
            propFlex="1"
            propWidth1="29px"
            propWidth2="29px"
            propWidth3="unset"
            propWidth4="96px"
            propWidth5="unset"
          />
        </div>
      </div>
      <div className={styles.facts}>
        <H1
          categoryLabel="my-fun-facts"
          propTop="0px"
          propLeft="0px"
          propHeight="unset"
          propWidth="unset"
          propRight="unset"
          propBottom="unset"
          propFontSize="32px"
          propFontSize1="32px"
        />
        <div className={styles.frameParent}>
          <div className={styles.factParent}>
            <Fact description="I like winter more than summer" />
            <Fact
              description="I often bike with my friends"
              propColor="#abb2bf"
            />
          </div>
          <div className={styles.factParent}>
            <Fact propColor="unset" />
            <Fact propColor="unset" />
          </div>
          <div className={styles.instanceGroup}>
            <Fact propColor="unset" />
            <Fact description="I am still in school" propColor="#abb2bf" />
          </div>
          <div className={styles.instanceWrapper}>
            <Fact description="I don’t have any siblings" propColor="#abb2bf" />
          </div>
        </div>
        <div className={styles.instanceContainer}>
          <Dots
            showEllipseDiv={false}
            ellipseDivVisible={false}
            ellipseDivVisible1={false}
            showFrameDiv
            ellipseDivVisible2={false}
            frameDivVisible={false}
            dotsWidth="unset"
            dotsHeight="unset"
            dotsPosition="absolute"
            dotsTop="0px"
            dotsLeft="0px"
            ellipseDivWidth="4px"
            ellipseDivHeight="4px"
            ellipseDivWidth1="4px"
            ellipseDivHeight1="4px"
            ellipseDivWidth2="4px"
            ellipseDivHeight2="4px"
            ellipseDivWidth3="4px"
            ellipseDivHeight3="4px"
            ellipseDivWidth4="4px"
            ellipseDivHeight4="4px"
            ellipseDivWidth5="4px"
            ellipseDivHeight5="4px"
            ellipseDivWidth6="4px"
            ellipseDivHeight6="4px"
            ellipseDivWidth7="4px"
            ellipseDivHeight7="4px"
            ellipseDivWidth8="4px"
            ellipseDivHeight8="4px"
            ellipseDivWidth9="4px"
            ellipseDivHeight9="4px"
            ellipseDivWidth10="4px"
            ellipseDivHeight10="4px"
            ellipseDivWidth11="4px"
            ellipseDivHeight11="4px"
            ellipseDivWidth12="4px"
            ellipseDivHeight12="4px"
            ellipseDivWidth13="4px"
            ellipseDivHeight13="4px"
            ellipseDivWidth14="4px"
            ellipseDivHeight14="4px"
            frameDivAlignSelf="stretch"
            frameDivWidth="unset"
            ellipseDivWidth15="4px"
            ellipseDivHeight15="4px"
            ellipseDivWidth16="4px"
            ellipseDivHeight16="4px"
            ellipseDivWidth17="4px"
            ellipseDivHeight17="4px"
            ellipseDivWidth18="4px"
            ellipseDivHeight18="4px"
            ellipseDivWidth19="4px"
            ellipseDivHeight19="4px"
            frameDivAlignSelf1="unset"
            frameDivWidth1="84px"
            ellipseDivWidth20="4px"
            ellipseDivHeight20="4px"
            ellipseDivWidth21="4px"
            ellipseDivHeight21="4px"
            ellipseDivWidth22="4px"
            ellipseDivHeight22="4px"
            ellipseDivWidth23="4px"
            ellipseDivHeight23="4px"
            ellipseDivWidth24="4px"
            ellipseDivHeight24="4px"
          />
          <img className={styles.logoIcon} alt="" src="/logo@2x.png" />
        </div>
      </div>
      <Header />
      <Media
        propTop="0px"
        propLeft="17px"
        propGap="8px"
        propWidth="1px"
        propHeight="191px"
        propGap1="8px"
        propWidth1="32px"
        propHeight1="32px"
        propWidth2="32px"
        propHeight2="32px"
        propWidth3="32px"
        propHeight3="32px"
      />
    </div>
  );
};

export default About;
